using System;

using Flower.Services;

namespace Flower.Tests;

// The one thing about the browser head that cannot be checked by running the
// app's own code: that a signature produced by WebCrypto is a signature this
// server accepts.
//
// Everything else in the browser's auth path is ordinary C# and is covered
// elsewhere. What is not ordinary is the boundary in webcrypto.js - three
// independent format choices (the curve, the public-key encoding, the signature
// encoding) that must line up with what SignatureVerifier expects, and that no
// managed test can exercise because crypto.subtle only exists in a browser.
//
// So this is a fixed vector, generated by running the real
// Flower.Web/wwwroot/webcrypto.js under a JS runtime and pasting what came out.
// If someone changes the curve, switches exportKey("raw") to "spki", or lets a
// signature come back DER-encoded, this fails - which is the whole point, since
// the alternative is discovering it as "the browser gets 401 on everything".
public class BrowserSignatureFormatTests
{
    // exportKey("raw") of a P-256 public key: 0x04 || X(32) || Y(32), which is
    // exactly what DeviceKeyStore.PublicKeyRaw builds for the desktop.
    private const string PublicKeyBase64 =
        "BE9m5s/LqPZNJtQ4ExI1B889CcGvLbOgD4y+BbyBV2Dd6z0lRPom7lc9yyd8HVs7DWmB9nshLTTcQY+T2xPXEhU=";

    // crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"}) over the canonical form
    // below. Raw r||s, which is what DSASignatureFormat
    // .IeeeP1363FixedFieldConcatenation means.
    private const string SignatureBase64 =
        "rB2j1CosapFdMMv7tCTpjJ6h7NKb2OR3z8+ZLOMnbYY6HKekhGBotozfl6t7lANiPX79yAuMvtnkz4V4fkVyhg==";

    private const string Timestamp = "1770000000";
    private const string Nonce = "9f86d081884c7d659a2feaa0c55ad015";

    // Passed as `now` so the vector does not expire: the clock-skew window is a
    // property of a live request, and this is testing bytes, not freshness.
    private static DateTimeOffset SignedAt => DateTimeOffset.FromUnixTimeSeconds(long.Parse(Timestamp));

    [Fact]
    public void A_signature_made_by_webcrypto_verifies_the_same_as_one_made_in_process()
    {
        var verified = SignatureVerifier.Verify(
            "GET", "/api/flower/v1/library", [("id", "al-1")], [],
            Timestamp, Nonce, SignatureBase64, PublicKeyBase64,
            SignedAt, new NonceReplayGuard(), "browser");

        Assert.True(verified);
    }

    [Fact]
    public void The_public_key_it_exports_is_the_shape_the_server_parses()
    {
        Assert.True(SignatureVerifier.TryParsePublicKey(PublicKeyBase64, out var point));
        Assert.Equal(32, point.X!.Length);
        Assert.Equal(32, point.Y!.Length);
    }

    // The tab's identity in the trust store is derived from that key, not
    // claimed - so the derivation has to be the same one every other head uses.
    [Fact]
    public void The_fingerprint_derived_from_it_is_an_ordinary_device_fingerprint()
    {
        var fingerprint = SignedRequestCanonicalizer.ComputeFingerprint(Convert.FromBase64String(PublicKeyBase64));

        Assert.Equal(32, fingerprint.Length);
        Assert.Matches("^[0-9a-f]+$", fingerprint);
    }

    // Cheap proof that the vector is load-bearing rather than tautological: the
    // same signature against a query it was not made over must fail.
    [Fact]
    public void The_vector_is_bound_to_what_it_was_signed_over()
    {
        var tampered = SignatureVerifier.Verify(
            "GET", "/api/flower/v1/library", [("id", "al-2")], [],
            Timestamp, Nonce, SignatureBase64, PublicKeyBase64,
            SignedAt, new NonceReplayGuard(), "browser");

        Assert.False(tampered);
    }
}
